:toc:
= jQAssistant Dashboard Plugin

The project provides a http://jqassistant.org/[jQAssistant] plugin for providing a https://github.com/softvis-research/jqa-dashboard/[dashboard],
which shows interactive graphics about different metrics of your system.
This allows you to have a quick overview about dependencies inside your project, statistics about your contributors, potential problems in your architecture and more.

== How It Works

The plugin provides a set of concepts, which are applied by jQAssistant, to enable the dashboard to function.
The dashboard itself will then be served as a React App under a certain URL (see <<HowTo, How To Use It>>)

Currently the dashboard provides:

- An overview page, which shows different metrics as numbers
- A structure diagram, which enables you to interactively explore your code base
- The distribution of file types, represented by a pie chart
- A dependency diagram, which shows you internal dependencies of your project
- An activity dashboard, that presents different statistics about the frequency and authors of the commits
- A knowledge distribution, showing what contributor uses what programming languages
- A hotspot diagram, that indicates potential risks in your code
- https://pmd.github.io/[Static code analysis]
- A test coverage diagram

== Prerequisites

- Java 8 or higher
- jQAssistant 1.7.0 or higher (see below)

[[HowTo]]
== How To Use It
You can use the plugin with Maven or with the Command Line Distribution of jQAssistant.

=== Maven

The plugin can be enabled in a Maven based project by adding it as a dependency to the jQAssistant Maven plugin:
----
<build>
    <plugins>
        <plugin>
            <groupId>com.buschmais.jqassistant</groupId>
            <artifactId>jqassistant-maven-plugin</artifactId>
            <version>1.7.0-SNAPSHOT</version>
            <executions>
                <execution>
                    <id>default-cli</id>
                    <goals>
                        <goal>scan</goal>
                        <goal>analyze</goal>
                    </goals>
                    <configuration>
                        <!-- Add jqassistant-dashboard:Default as a jQA group-->
                        <groups>
                            <group>jqassistant-dashboard:Default</group>
                            <group>default</group>
                        </groups>
                        <!-- Include .git folder path as a scan location -->
                        <scanIncludes>
                            <scanInclude>
                                <path>${project.basedir}/.git</path>
                            </scanInclude>
                        </scanIncludes>
                    </configuration>
                </execution>
            </executions>
            <!-- Add the jqassistant-dashboard-plugin itself as a dependency-->
            <dependencies>
                <dependency>
                    <groupId>org.jqassistant.contrib.plugin</groupId>
                    <artifactId>jqassistant-dashboard-plugin</artifactId>
                    <version>1.7.0-SNAPSHOT</version>
                </dependency>
            </dependencies>
        </plugin>
    </plugins>
</build>
----

After building the project (e.g. with mvn clean install), you need to start the jQAssistant server with
----
mvn jqassistant:server
----

If the server started successfully, you can reach the dashboard under

http://localhost:7474/jqassistant/dashboard

Note, that the regular Neo4j Browser is still available (http://localhost:7474/browser/).

=== Command Line Distribution

To enable the plugin with the Command Line Distribution, download the JAR file from Maven Central and put it in the /plugins folder from the distribution.

In addition to that, you need to install the https://github.com/kontext-e/jqassistant-plugins[jQA Git Plugin].

To start the jQA server run the following commands: (xxx.jar ist your built project jar file)

Linux:
----
sh bin/jqassistant.sh scan -f .../xxx.jar
sh bin/jqassistant.sh scan -f .../.git/
sh bin/jqassistant.sh analyze -groups jqassistant-dashboard:Default
sh bin/jqassistant.sh server
----

Windows:
----
bin\jqassistant.cmd scan -f ...\xxx.jar
bin\jqassistant.cmd scan -f ...\.git\
bin\jqassistant.cmd analyze -groups jqassistant-dashboard:Default
bin\jqassistant.cmd server
----


== Acknowledgements

The plugin could not provide its functionality without the support of the following open source projects:

* https://github.com/softvis-research/jqa-dashboard/[jQA-Dashboard]
* https://jqassistant.org[jQAssistant]
* https://neo4j.org[Neo4j]


